#Forge
name: Scoreboard.js
author: tbleckert
category: Widgets
tags: [sport, html, data, events, alert]
docs: http://tobiasbleckert.se/Scoreboard.js/
demo: http://scoreboardjs.tb-one.se/demos/messages.html
current: 0.1